include: package:flutter_lints/flutter.yaml

name: game_template
description: 다양한 게임을 구현하는 기본 템플릿.
publish_to: 'none'

version: 1.0.0+1

# 이 프로젝트가 실행되어야 할 flutter SDK의 버전(2.19.6 <= version < 4.0.0)
environment:
  sdk: '>=2.19.6 <4.0.0'

# 앱 `실행`에 필요한 라이브러리
dependencies:
  flutter:
    sdk: flutter

  # iOS용 아이콘 사용
  cupertino_icons: ^1.0.2

  # 추가!!
  # 오디오파일 재생(캐시, 이어듣기, 볼륨조절, 상테 업데이트 등 지원)
  audioplayers: ^4.0.1            # ^3.0.0
  # 페이지 라우팅 제공
  go_router: ^6.5.7               # ^6.0.1
  # 상태관리 지원(기존 상태관리보다 더 쉽게 상태를 관리할 수 있게 지원함)
  provider: ^6.0.5                # ^6.0.2
  # 로컬에 데이터를 CRUD할 수 있음(하이브와 유사하게 Key:Value 쌍으로 구현됨)
  # 일반적으로 로그인정보, 사용자 설정 정보, 앱 상태 정보 등을 저장할 때 사용
  shared_preferences: ^2.1.0      # ^2.0.13

  logging: ^1.1.1

  # 파이어베이스 핵심 기능
  firebase_core: ^2.9.0           # ^2.1.1
  # 파이어베이스 충돌정보 수집 및 분석
  firebase_crashlytics: ^3.1.0    # ^3.0.3
  # Google Play 게임 서비스 API를 사용하여 게임에 기능을 추가하는 역할
  games_services: ^3.0.1
  # 광고
  google_mobile_ads: ^2.4.0       # ^2.0.1, Ads
  # 인앱결재
  in_app_purchase: ^3.1.5         # ^3.0.1  # In-app purchases
  # 메시지 번역, 복수형 및 성별, 날짜/숫자 서식, 양방향 텍스트 등 국제화 및 지역화 기능 지원
  intl: ^0.18.1

# 앱 `개발`에 필요한 라이브러리
# 테스트 도구, 코드 스타일 가이드 도구, 코드 생성 도구 등.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

analyzer:
  language:
    strict-casts: true
    strict-inference: true

linter:
  rules:
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    package_api_docs: true
    package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unawaited_futures: true
    unnecessary_statements: true
    use_super_parameters: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"

